#Day 3 Practice
rm(list = ls())
library(here)
source(here::here("data/day3_objects.R"))


gapminder07 %>% ggplot(aes(x = gdpPercap, y = lifeExp)) + 
    geom_point() + 
    labs(title = "Relationship between life expectancy and GDP per capita in 2007", 
         x = "GDP per capita", y = "Life expectancy")+
    theme_bw()

gapminder07 %>% ggplot(aes(x = log(pop), y = log(gdpPercap)))+
    geom_point()+
    labs(title = "Relationship between the natural log of GDP per capita and the natural log of population in 2007",
         x = "natural log of population", y = "natural log of GDP per capita")

long_gen %>% group_by(datetime) %>% summarise(total_output_daytime = sum(output)) %>% 
    ggplot(aes(x = datetime, y = total_output_daytime)) + geom_col() + 
    labs(title="Total energy generated, by hour", x="Hour", y="Output (MW)")

generation %>% mutate(total_hydro = large_hydro+small_hydro) %>% select(datetime, total_hydro) %>% 
    ggplot(aes(x = datetime, y = total_hydro)) + geom_col()+ 
    labs(title="Total hydro energy generated, by hour", x="Hour", y="Output (MW)")

#if use long_gen table
long_gen %>% 
    filter(source=="large_hydro"|source=="small_hydro") %>%
    group_by(datetime) %>% 
    summarise(output=sum(output)) %>%
    ggplot() + 
    geom_col(aes(x=datetime, y=output)) + 
    labs(title="Total hydro power generated, by hour", x="Hour", y="Output (MW)")

#geom_line()
imports %>%
    ggplot(aes(x=datetime, y=imports)) + 
    geom_line(size = 1.2, col = 'red') + 
    labs(title="Energy imports over time", x="Hour", y="Amount imported (MW)")

generation %>% 
    ggplot() + 
    geom_area(aes(x=datetime, y=wind), fill="darkblue") + 
    labs(title="Hourly wind power generation, Sept 3-9", x="Hour", y="Output (MW)")

long_gen %>% 
    ggplot() + 
    geom_boxplot(aes(x=source, y=output)) + 
    labs(title="Amount of energy generated by each source, Sept 3-9", x="Source type", y="Output (MW)")

long_gen %>% filter(source == 'large_hydro') %>% 
    ggplot(aes(x = datetime, y = output))+
    geom_line()+
    geom_smooth()

long_gen %>% group_by(source) %>% summarise(total_output=sum(output)) %>% 
    ggplot(aes(x=source, y = total_output))+
    geom_col(fill='darkred')+
    geom_hline(aes(yintercept = mean(total_output)))+
    geom_hline(aes(yintercept = median(total_output), col='green'))
    
#Labels
imports %>%
    ggplot() + 
    geom_line(aes(x=datetime, y=imports), col="red") + 
    labs(title="Energy imports over time in California", subtitle="Hourly data from September 3-9, 2018",
         caption="Source: California Energy Commission", x="Hour", y="Amount imported (MW)")


imports %>%
    ggplot(aes(x=datetime, y=imports)) + 
    geom_line(col = 'red') + 
    scale_x_datetime(date_labels="%H:%M", date_breaks="12 hours") +
    labs(title="Energy imports over time in California", 
         subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Amount imported (MW)")+
    theme_minimal()


imports %>%
    ggplot() + geom_line(aes(x=datetime, y=imports), col="red") + 
    scale_x_datetime(date_labels="%H:%M", date_breaks="12 hours") +
    labs(title="Energy imports over time in California", subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Amount imported (MW)") + 
    theme(axis.text.x=element_text(angle=45, hjust=1, size=12))


long_merged_energy %>%
    ggplot() + 
    geom_line(aes(x=datetime, y=output, group=source, col=source)) + 
    labs(title="Output by energy source over time", 
         subtitle="Hourly data from September 3-9, 2018", 
         x="Hour", y="Output (MW)")

long_gen %>% filter(source %in% c('wind','solar','geothermal')) %>% 
    ggplot(aes(x=datetime,y=output,group=source,col=source))+
    geom_line(size = 1.5)

long_gen %>% 
    ggplot() + 
    geom_line(aes(x = datetime, y = output)) + 
    facet_wrap(~source) + 
    labs(title="Generation over time, by energy source", subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Output (MW)")

long_gen %>% 
    ggplot() + 
    geom_line(aes(x = datetime, y = output)) + 
    facet_wrap(~source, scales="free") + 
    labs(title="Generation over time, by energy source", subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Output (MW)")

long_gen_regroup <- long_gen %>%
    rename(type = source) %>% 
    merge(regroup, by="type")

head(long_gen_regroup)
long_gen_regroup %>% ggplot() + 
    geom_line(aes(x=datetime, y=output, group=group, col=group), size=1) + 
    scale_color_brewer(palette="Set1", name="Type of energy source") +
    facet_wrap(~type, scales="free") + 
    labs(title="Generation over time, by energy source", subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Output (MW)") + 
    theme(legend.position = "bottom")
